doc/src/extensions.rst, doc/src/module.rst, lib/__init__.py, lib/extensions.py, psycopg/psycopgmodule.c, setup.py, tests/test_module.py, tests/testutils.py
=> Add libpq version discovery

psycopg/config.h
Recently, Python 3.5 was released, which also changed the default compiler used on Windows to MSVC 2015. Psycopg2 did not yet compile under this version of MSVC.
The fixes are simple:
* `isnan` is a macro that MSVC did not define in older version, the code just assumed it wasn't present in all versions, fixed so that it only re-defines it when it is really not existent
* `round` is a function that MSVC did previously not define, now they do, fixed by checking for a specific version
I've never contributed to this project, so please let me know if you want to see things differently :)
=> Fixes for MSVC 2015 (Python 3.5)

doc/src/extensions.rst, doc/src/module.rst, lib/__init__.py, lib/extensions.py, psycopg/psycopgmodule.c, tests/test_connection.py
Calls PQconninfoParse to parse the dsn into a list of keyword and value
structs, then constructs a dictionary from that.  Can be useful when one
needs to alter some part of the the connection string reliably, but
doesn't want to get into all the details of parsing a dsn string:
quoting, URL format, etc.
=> Add parse_dsn module function

doc/src/extensions.rst, lib/extensions.py, psycopg/psycopgmodule.c, psycopg/utils.c, tests/test_quote.py
@dvarrazzo how about this way? #308
The compose stuff looks nice, but I only need something really simple and straightforward for #322: https://github.com/psycopg/psycopg2/pull/322/files#diff-e6256dfa32f9bced2faae91403f4d594R487
=> Add psycopg2.extensions.quote_ident.

doc/src/conf.py
otherwise, when building from unchanged source in 2018,
it would claim Copyright 2018
which is not true
Being able to reproduce identical output from identical input
is important to Linux distributions
=> dont claim copyright for future years

doc/src/install.rst
pip is becoming the standard method for installing python packages, and now binary wheels are a better and easier option for users:
https://github.com/psycopg/psycopg2/issues/368
=> Suggest installing psycopg2 in windows using pip

psycopg/adapter_datetime.c
Found by clang static analyzer
=> Avoid a possible null deref, tz might be NULL.

setup.py
Also normalized the result and made sure that if PostgreSQL ever starts
using just integer version numbers (as in "10") everything still works.
=> Fixed version regexp to match "10devel"

.appveyor.yml, scripts/appveyor.cache_rebuild, setup.py
In setup.py, changed the manifest check to only add the manifest when compiling with VC9 compiler instead of >= VC9.  Fixes #541 
Updated appveyor.yml to link against newer versions of OpenSSL and PostgreSQL.
Updated the runtime server version so the tests are now run against a PostgreSQL 9.6 server.
=> Remove VC9 Runtime dependency and update appveyor.yml to newer versions

doc/src/tools/lib/dbapi_extension.py
In sphinx-doc/sphinx@1a821b89e9952fc2, the deprecated `make_admonition()` function was removed.
This pull request updates the code to use the modern API instead. Also `Directive` is imported from `docutils.parsers.rst`, as import from `sphinx.util.compat` is deprecated since sphinx-doc/sphinx@2df0bb8d03d05fe7.
=> Make dbapi_extension.py compatible with Sphinx 1.6

lib/extras.py, tests/__init__.py, tests/test_async.py, tests/test_async_keyword.py, tests/test_cancel.py, tests/test_connection.py, tests/test_copy.py, tests/test_errcodes.py, tests/test_module.py, tests/test_transaction.py, tests/test_types_basic.py, tests/test_types_extras.py, tests/test_with.py, tests/testutils.py
The syntax `except Exception, exc:` is deprecated. All Python versions supported by psycopg2 support the newer, modern syntax. Forward compatible with future Python versions.
=> Use modern except syntax throughout project

doc/src/extras.rst, lib/extras.py, tests/test_cursor.py, tests/test_extras_dictcursor.py, tests/test_types_extras.py, tests/testutils.py
namedtuple is available on all Python versions supported by psycopg2. It was first introduced in Python 2.6. Can remove all workarounds and special documentation.
=> Remove workarounds for namedtuple on Python <= 2.5

tests/test_copy.py, tests/testutils.py
`io.TextIOBase` is available on all Python versions supported by psycopg2. Can remove all workarounds.
=> Remove io.TextIOBase workaround for Python <= 2.5

tests/testutils.py
uuid is available on all Python versions supported by psycopg2.
=> Remove uuid workaround for older Pythons

tests/test_module.py, tests/test_types_basic.py
psycopg2 does not support Python < 2.6, remove all test guards for these versions.
=> Remove use of skip_before_python for unsupported Python versions

lib/__init__.py, tests/test_cursor.py
The decimal module is available on all Python versions supported by psycopg2. It has been available since Python 2.4. No need to catch an `ImportError`.
https://docs.python.org/2/library/decimal.html
=> Remove workaround for decimal module

psycopg/pqpath.c, psycopg/solaris_support.c, psycopg/solaris_support.h, setup.py
Solaris does not have timeradd and timersub. Add solaris_support.c which
provides emulated versions of them on Solaris.
=> Emulate timeradd and timersub on Solaris

lib/extras.py
On Python3 MinTimeLoggingConnection raises an exception as it tries to
mix strings and bytes. Fixes #609
=> Patch for issue #609 for MinTimeLoggingConnection

tests/test_types_extras.py, tests/test_with.py
All versions of Python supported by psycopg2 have builtin support for the with statement. The import is unnecessary noise.
=> Remove "from __future__ import with_statement"

doc/src/extras.rst, lib/_json.py
The docs don't need to describe what will happen on Python versions before 2.6 as they are unsupported by psycopg2.
Should have been included in commit d58844e5483483240f97537e9a77b4e79cea2ab3, but was missed.
=> Update documentation to reflect JSON import behavior

tests/__init__.py, tests/test_async.py, tests/test_async_keyword.py, tests/test_cancel.py, tests/test_copy.py, tests/test_cursor.py, tests/test_dates.py, tests/test_errcodes.py, tests/test_extras_dictcursor.py, tests/test_fast_executemany.py, tests/test_ipaddress.py, tests/test_lobject.py, tests/test_module.py, tests/test_notify.py, tests/test_psycopg2_dbapi20.py, tests/test_quote.py, tests/test_replication.py, tests/test_sql.py, tests/test_transaction.py, tests/test_types_basic.py, tests/test_types_extras.py, tests/test_with.py
There is no need to import `testutils.unittest` instead of simply `unittest`. They are simple aliases. Use system `unittest` to be more regular, consistent as well as idiomatic with the wider Python community.
=> Always import the system unittest

tests/test_types_extras.py
Not compatible with Python3. Makes the code more forward compatible with modern Pythons.
In Python2, it was an alternative syntax for octal.
```
$ python3
>>> 01
File "<stdin>", line 1
01
^
SyntaxError: invalid token
```
=> Drop leading 0's from numeric literals

doc/src/tools/stitch_text.py, lib/extras.py, lib/sql.py, tests/test_cursor.py, tests/test_extras_dictcursor.py, tests/test_sql.py
Available since Python 2.6. Use of `.next()` is deprecated and not supported in Python 3. Forward compatible with modern Python.
https://docs.python.org/2/library/functions.html#next
=> Use builtin function next() throughout project

examples/dialtone.py
Introduced in Python 2.4 and the oldest supported Python is 2.7.
https://docs.python.org/2/library/functions.html#sorted
=> Remove sorted() workaround; available on all supported Pythons

tests/test_connection.py, tests/test_copy.py, tests/test_module.py, tests/test_notify.py, tests/testutils.py
Part of the work towards moving tests out of the installed package.
=> Remove unnecessary script_to_py3; make scripts compatible instead

NEWS, doc/src/extras.rst, doc/src/usage.rst, lib/extras.py
Deprecated in commit b263fbf274f9085a1bddca018ed8a50d37023fc7 on 2010-01-13. The deprecation warning was first released in version 2.2.2. 
The function used to register an alternate type caster for `TIMESTAMP WITH TIME ZONE` to deal with historical time zones with seconds in the UTC offset. These are now correctly handled by the default type caster, so currently the function was changed to not do anything (a no-op).
=> Drop long deprecated function register_tstz_w_secs()

psycopg/adapter_datetime.c, psycopg/python.h
=> use accessor macros for pypy3 compatibility

.travis.yml
Also, switch to wheel, because eggs caused problems on 3.7:
ValueError: bad marshal data (unknown type code)
=> Travis CI: Run tests on Python 3.7

NEWS, lib/_ipaddress.py, lib/_range.py, lib/compat.py, lib/errorcodes.py, lib/extensions.py, lib/extras.py, lib/pool.py, lib/sql.py, scripts/make_errorcodes.py, setup.py, tests/test_cursor.py, tests/test_sql.py, tests/testutils.py
Make all library code compatible with both Python 2 and Python 3. Helps move to modern Python idioms. Can now write for Python 3 (with workarounds for Python 2) instead of the other way around.
In the future, when it is eventually time to drop Python 2, the library will be in a better position to remove workarounds
Added a very small compatability module compat.py where required. It includes definitions for:
- `text_type` -- A type. `str` on Python 3. `unicode` on Python 2.
- `string_types` -- A tuple. Contains only `str` on Python 3. Contains `str` & `unicode` on Python 2.
=> Drop 2to3 build step; make all code compatible with all Pythons

doc/src/usage.rst
As discussed in issue #785, add a note to the documentation about backslashes and LIKE/ILIKE.
=> Add documentation about the use of backslashes with LIKE

scripts/refcounter.py
Per https://docs.python.org/3/library/optparse.html
> Deprecated since version 3.2: The optparse module is deprecated and
> will not be developed further; development will continue with the
> argparse module.
=> Replace deprecated optparse usage with argparse

setup.py
distutils is not recommended for use and unnecessary for modern Python
environments. Use only setuptools instead. From
https://docs.python.org/3/library/distutils.html:
> Most Python users will not want to use this module directly, but
> instead use the cross-version tools maintained by the Python Packaging
> Authority. In particular, setuptools is an enhanced alternative to
> distutils ...
>
> The recommended pip installer runs all setup.py scripts with
> setuptools, even if the script itself only imports distutils. Refer to
> the Python Packaging User Guide for more information.
=> Drop legacy distutils fallback in setup.py

.appveyor.yml
Python 3.3 has been unsupported since
c2d082e896e7bcb81231603404e7d4789e56cf00.
=> Remove Python 3.3 references from appveyor.yml

psycopg/psycopgmodule.c, tests/test_quote.py
Per http://initd.org/psycopg/docs/install.html#prerequisites:
> PostgreSQL client library version from 9.1
=> Remove workarounds for unsupported libpq < 9.1

tests/test_ipaddress.py, tests/testutils.py
Skip tests as early as possible by decorating the whole class with `unittest.skipIf` instead of every test method individually.
=> Simplify 'decorate_all_tests' usage by decorating the test class

NEWS, doc/src/extras.rst, lib/extras.py, tests/test_fast_executemany.py
We found it useful in our project to improve `psycopg.extras.execute_values` in such a way that it supports `RETURNING` clause of query being executed.
=> add RETURNING clause support in execute_values function

doc/src/advanced.rst, doc/src/extras.rst, lib/extras.py, psycopg/pqpath.c, psycopg/pqpath.h, psycopg/replication_cursor.h, psycopg/replication_cursor_type.c, psycopg/solaris_support.h, psycopg/win32_support.h, tests/test_async_keyword.py, tests/test_replication.py
This commit makes psycopg2 responsible for sending the status update (feedback) messages to the server regardless of whether a synchronous or asynchronous connection is used.
Feedback is sent every *status_interval* (default value is 10) seconds, which could be configured by passing a corresponding parameter to the `start_replication()` or `start_replication_expert()` methods.
The actual feedback message is sent by the `pq_read_replication_message()` when the *status_interval* timeout is reached.
The default behavior of the `send_feedback()` method is changed. It doesn't send a feedback message on every call anymore but just updates internal structures. There is still a way to *force* sending a message if *force* or *reply* parameters are set.
The new approach has certain advantages:
1. …
=> Smart replication feedback

lib/extras.py, tests/test_extras_dictcursor.py
I've finally gotten around to testing @dvarrazzo's solution to #838. Unfortunately it doesn't fully work.
The problem is that the `lru_cache` function was used to wrap a non-static method, so it receives `self` as first argument instead of only receiving `key` as intended, and since `self` (the cursor) isn't always the same object, the cache misses.
The fix is a little akward because the `lru_cache` decorator doesn't play well with `classmethod` and `staticmethod` (it took me a while to find a way that works).
=> Fix namedtuple cache

.travis.yml, doc/src/install.rst, setup.py, tox.ini
Python 3.8 was released on October 14th, 2019.
- Added 'Programming Language :: Python :: 3.8' trove classifier.
- Added 'py38' to the tox test matrix.
- Added 'python: 3.8' to the Travis test matrix.
- Removed 'dist: xenial' from Travis configuration; it is now the
default.
- Removed 'dist: trusty' from Travis configuration; it is not longer
necessary.
- Removed 'sudo' from Travis configuration; it is deprecated.
https://docs.python.org/3.8/whatsnew/3.8.html
=> Add Python 3.8 to the test matrix

doc/src/install.rst
The CFFI port works much better on PyPy and has been used in production before.
The documentation mentioned the Ctypes port but not the CFFI port.
I added it to the documentation.
=> Mention the CFFI port to Psycopg2 in documentation

psycopg/aix_support.c, psycopg/aix_support.h, psycopg/pqpath.c, setup.py
AIX has the same issue as Solaris no .timeradd or .timersub
```
ld: 0711-317 ERROR: Undefined symbol: .timeradd
ld: 0711-317 ERROR: Undefined symbol: .timersub
```
This patch was derived from solaris_support.h and solaris_support.c
Resolves #105
=> feat: Add AIX support

psycopg/connection_int.c
If the specified encoding is the same as the current one,
the early exit did not release the clean_enc string allocated
by clear_encoding_name.
=> Fix memory leak in conn_set_client_encoding

NEWS, setup.py
We use mxDateTime in our old codebase. Right now the only way to compile this is by editing setup.cfg
This patch lets setup.py find the mxDateTime headers automatically.
=> Find mxDateTime.h automatically

doc/src/connection.rst
Original example ctypes code causes an error:
```python
libpq = ctypes.pydll.LoadLibrary(ctypes.util.find_library('pq'))
AttributeError: module 'ctypes' has no attribute 'util'
```
Adding `import ctypes.util` fixes the issue
=> Fix ctypes doc example AttributeError

tests/test_connection.py
Previously, this test had a bug, because if the CREATE TABLE statement
failed, the setup would fail without committing or rolling back the
active transaction.
This is needed because `tearDown` is not called if there was an error
during `setUp` ([as specified by the `unittest` docs](https://docs.python.org/3/library/unittest.html#unittest.TestCase.tearDown)).
=> Handle failure in setup of ConnectionTwoPhaseTest

tests/test_connection.py
If the CREATE TABLE statement fails, the setup would fail
without committing or rolling back the active transaction, so the
transaction would hold onto its resources indefinitely.
Normally, the transaction would be closed when the connection is closed
in the `tearDown` function. However, `tearDown` is not called if there
was an error during `setUp` ([as specified by the `unittest` docs](https://docs.python.org/3/library/unittest.html#unittest.TestCase.tearDown)), so
we need to handle this case specially.
=> Handle failure in setup of IsolationLevelsTestCase

doc/src/install.rst
Following up on a [conversation](https://github.com/psycopg/psycopg2/issues/1085#issuecomment-659028139) I'd started with @dvarrazzo 
----
Using `psycopg-binary` is the fastest way for most folks to get up-and-running with psycopg. We've seen a lot of noise in the GH issues with people failing to install the non-binary version. Hopefully this will make life easier for people new to psycopg/python, and cut down on issue maintenance for the project maintainers ❤️ 
See https://github.com/psycopg/psycopg2/issues/1085#issuecomment-659028139
I apologize that I'm not super familiar with rst or Sphinx (and I had trouble getting the docs to build on master), and also not super familiar with the inner workings of psycopg. Mostly just hoping to start a discussion here, and work through a way to …
=> Move pyscopg-binary install docs to "quick start" section

doc/src/extras.rst, lib/extras.py
Just to remind that the object received is a mapping in python sense, so it will work with double-asterisk unpacking and other fancy things. I deliberately don't promise it'll be an OrderedDict forever, as we may want to change it one day.
=> DictCursor docs improvement

.travis.yml, scripts/travis_prepare.sh, scripts/travis_test.sh
- Added ARM64 jobs in Travis-CI 
- Updated global variables in scripts `travis_test.sh` and `travis_prepare.sh`
Signed-off-by: odidev <odidev@puresoftware.com>
=> Add ARM64 jobs in Travis-CI

doc/src/install.rst, scripts/travis_prepare.sh, scripts/travis_test.sh
Since 2020-09-24 PostgreSQL is no longer the future 😃 
I added PostgreSQL 13 to run as part of the build pipeline and updated the docs to reflect support for version 13 as well.
Feel free to tell me if anything is missing, thanks!
=> Add support for PostgreSQL 13 (final)

.appveyor.yml, NEWS, doc/src/install.rst, psycopg/python.h, scripts/appveyor.py, setup.py, tox.ini
=> Drop support for EOL Python 3.4

doc/src/install.rst
=> Fix typo in sample code in install.rst: psycopg >> psycopg2

.appveyor.yml, scripts/appveyor.cache_rebuild, scripts/appveyor.py
Removed support for building Python 2.7 and 3.4 binaries in AppVeyor and changed PostgreSQL libpq library linkage from version 11.x to 13.0.  Version of Postgres > 11 do not have build support for Visual Studio versions before 2013 requiring dropping support of versions of Python that are built against older version (Python 2.7 uses 2008 and Python 3.4 uses 2010).
=> Removed Windows builds for Python 2.7/3.4 and link against libpq 13.0

NEWS, psycopg/error_type.c, tests/test_errors.py
tl;dr: conform with [PEP 249](https://www.python.org/dev/peps/pep-0249/#operationalerror`) better, so that libraries can treat disconnect errors caused by PgBouncer as transient.
DatabaseError is too broad and is considered **not** transient failure by libraries, which causes failures where an operation could simply be re-tried, like [relstorage:drivers.py#L157](https://github.com/zodb/relstorage/blob/9568c6b1447275fc8983ee025b28181218ae456b/src/relstorage/adapters/drivers.py#L157) or [pjpersist:datamanager.py#L100](https://github.com/Shoobx/pjpersist/blob/1c4ba9df7c71b621f87c25e0646352b3b74be5df/src/pjpersist/datamanager.py#L100)
A real world example: conntect to PgBouncer instead of Postgres directly.  Now, if the Postgres server is disrupted, you get a ProtocolViolation (SqlState …
=> Classify SqlState Connection Exceptions as operational errors

tests/test_module.py
Previously, the CRDB's pg server version was 9.5, which meant this test
wasn't run as it is skipped for versions 9.6 and before. Now that the
server version of CRDB is 13, this check no longer applies.
This patch explicitly skips test_9_6_diagnostics for CRDB. The reason
for this is the same as test_9_3_diagnostics, which is currently
skipped for CRDB.
=> Skip test_9_6_diagnostics test for CRDB

.appveyor.yml, scripts/appveyor.cache_rebuild, scripts/appveyor.py
Changes to allow building the Window binaries in AppVeyor against the latest version of the Postgres 11.x code, currently at version 11.10.
=> Allow Windows building against the lastest Postgres 11.x code

doc/src/extras.rst
It's not obvious that you cannot call `send_feedback()` on a temporary Cursor, and took me a long time to debug why it wasn't working. Improve the docs by making it clearer.
=> Add warning about send_feedback and cursor choice

.github/ISSUE_TEMPLATE/problem-installing-psycopg2.md, .github/workflows/packages.yml, NEWS, scripts/build/build_musllinux_1_1.sh
I'm back for some more `musllinux` support. Since psycopg2 is still needed for Django, I figured I'd try to add support here as well.
The artifacts can be found here: https://github.com/lithammer/psycopg2/actions/runs/1564148387
=> Build `musllinux` wheels

tests/test_async.py, tests/test_cursor.py, tests/test_extras_dictcursor.py, tests/test_green.py, tests/test_with.py, tests/testutils.py
CockroachDB supports named cursors in v22.1, so more tests pass.
=> Unskip tests that work on CockroachDB v22.1

lib/_range.py
It is not used in python3, but python2 is no longer supported: https://github.com/python-babel/babel/blob/d8584405a66a79d79bed44b5d80df0bc89f8eee3/setup.py#L59
=> Remove `__nonzero__` method

doc/src/cursor.rst, doc/src/extras.rst
I had somehow forgotten about https://github.com/psycopg/psycopg2/pull/834 and could not fix the issues in that branch as I have no access to it somehow... Here is a new PR with the requested changes. I don't remember if I tested building the docs with this back in 2019, the syntax for the `extras.rst` might be broken but I know nothing about RST.
My original text: "hopefully this will make those functions more approachable for newbies. everyone tries it without proper sequences and then has to google."
=> Add executemany & execute_batch examples

doc/src/usage.rst
Hi,
A tiny little typo fixed :)
Thanks for your library.
=> fix typo in Usage.html page in documentation

tests/test_connection.py
PG15 changed the semantics of some ssl attributes (#1506), and a very similar regression test failure has now been observed again with PG16. Disable the test for now.
=> Disable test_ssl_attribute on PG16+

doc/src/module.rst
This is a minor improvement for the doc.
=> Use `except psycopg2.Error as e` in example.

NEWS, setup.py
- Differentiate between unexpected empty values and execution failure.
- Accept empty `--cppflags` and `--ldflags` output. Fixes #1599.
- Accept UTF-8 output from pg_config, for alternative client locales.
------
I took this opportunity to simplify a bit using `subprocess.run()`, since it looks like the minimum Python version is now 3.6. 
Originally I planned to set `run(..., encoding='ascii')`, but I realized that standard error messages coming back are not guaranteed to be in ASCII. So I switched to UTF-8 decoding (strict for stdout, lax for stderr), which should also handle more unusual installation paths. If that's too much change for a single bugfix, I can revert to ASCII-only.
=> setup.py: handle more corner cases for pg_config

NEWS, psycopg/psycopgmodule.c
Previously, any exceptions raised during initialization were swallowed with a message like
SystemError: initialization of _psycopg raised unreported exception
Fixes #1598.
=> Return NULL on failed module initialization

.github/workflows/docs.yml, .github/workflows/packages.yml, .github/workflows/tests.yml
After updating all GitHub actions I saw that old Postgres versions were used, so I updated them to 16 as well.
* build-sdist used 13
* build-linux used 14 (but libpq 16)
=> chore: update GitHub actions and Postgres image tags

.github/dependabot.yml
Let bots do some of the tedious work 😄
=> chore: Let dependabot update GitHub actions

psycopg/lobject_type.c
I'm not sure what the correct syntax should be, since 3.9 uses Union[t1, t2] for representing multiple types.
=> Document bytes as another valid input type for lobject.write()

.github/workflows/tests.yml, NEWS, psycopg/utils.c, setup.py, tests/test_ipaddress.py, tox.ini
See individual commits.
I don't have all the bits to run tests, but I used these changes to build psycopg2 in Fedora and tests with Python 3.13 passed.
It would probably be good to add 3.13 to CI, but I'm not sure about the desired version matrix, so haven't done any changes there.
Related to #1692.
=> Add support for Python 3.13

doc/src/usage.rst
Thanks very much for the work you do maintaining this @dvarrazzo ! :)
Here's a tiny grammar fix in the docs I came across which makes the sentence easier to understand.
=> docs: tiny grammar fix "a" -> "one"

doc/src/usage.rst
While going through the psycopg2 documentation, I encountered a typo in the docs. So I thought to drop a quick fix.
=> docs: fixed a typo in doc/src/usage.rst file

NEWS, psycopg/connection_int.c, psycopg/pqpath.c, tests/test_notify.py
This fixes the issue that asynchronous notifications are not fetched during the commit https://github.com/psycopg/psycopg2/issues/1727.
=> Adds notifies processing during commit

.github/workflows/packages.yml, scripts/build/build_libpq.sh, scripts/build/wheel_macos_before_all.sh, tests/test_async.py, tests/test_green.py
Homebrew binaries are always compiled for exactly the version they're installed on making them very unportable. When a wheel is "repaired" by cibuildwheel, delocate-wheel pulls in _psycopg's dependencies (libpq.dylib, libssl.dylib and libcrypto.dylib) which, on a GitHub Actions macOS 14 runner, are provided by Homebrew and are therefore only macOS >= 14 compatible. The resultant wheel is therefore incompatible with all but the latest macOS versions.
Build all dependencies from source so that we can set the deployment target to something sensible. Fixes #1753.
=> ci(macos): Avoid linking against Homebrew
